name: CI

on:
  push:
  pull_request:
    branches: main

env:
  cache-name: build-cache

jobs:
  build_cpp:
    name: Build C++
    env:
      cwd: cpp

    runs-on: windows-latest
    defaults:
      run:
        working-directory: ${{ env.cwd }}

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Set up Zig
        uses: goto-bus-stop/setup-zig@v2

      - name: Restore or create cache
        uses: actions/cache@v3
        env:
          cache-key: ${{ env.cache-name }}-${{ runner.os }}
        with:
          path: |
             ${{ env.cwd }}/zig-out
             ${{ env.cwd }}/zig-cache
          key: ${{ env.cache-key }}
          restore-keys: ${{ env.cache-key }}

      # Where the magic happens :sparkle:

      - name: Build code
        run: zig build

      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: |
            ${{ env.cwd }}/src
            ${{ env.cwd }}/zig-out
            ${{ env.cwd }}/README.md
