name: CI

on:
  push:
  pull_request:
    branches: main

env:
  cache-name: build-cache    

jobs:
  zig_build:
    name: Zig Build
    env:
      cwd: ${{ matrix.cwd }}
    strategy:
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
        cwd:
          - cpp
          - zig

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ${{ env.cwd }}

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Set up Zig
        uses: goto-bus-stop/setup-zig@v2

      - name: Add cache
        uses: actions/cache@v3
        env:
          base-key: ${{ env.cache-name }}-${{ runner.os }}
        with:
          path: |
             ${{ env.cwd }}/zig-out
             ${{ env.cwd }}/zig-cache
          key: ${{ env.base-key }}-${{ env.cwd }}
          restore-keys: ${{ env.base-key }}

      # Where the magic happens :sparkle:

      - name: Build code
        run: zig build --verbose --summary all --color on
      # - name: Test code
      #   run: zig test

      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: build-${{ runner.os }}-${{ env.cwd }}
          path: |
            ${{ env.cwd }}/src
            ${{ env.cwd }}/zig-out
            ${{ env.cwd }}/README.md

  rs_build:
    name: Rust Build
    env:
      cwd: rs
    strategy:
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
        toolchain:
          - stable
          - beta
          - nightly

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ${{ env.cwd }}

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Add cache
        uses: actions/cache@v3
        env:
          base-key: ${{ env.cache-name }}-${{ runner.os }}
        with:
          path: |
             ${{ env.cwd }}/target
             ${{ env.cwd }}/Cargo.lock
          key: ${{ env.base-key }}-${{ env.cwd }}
          restore-keys: ${{ env.base-key }}

      # Where the magic happens :sparkle:

      - name: Set up Rust toolchain
        run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - name: Build code
        run: cargo build --verbose --color always
      # - name: Test code
      #   run: cargo test --verbose

      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: build-${{ runner.os }}-${{ env.cwd }}
          path: |
            ${{ env.cwd }}/src
            ${{ env.cwd }}/target
            ${{ env.cwd }}/README.md
